[2025-05-15T10:21:49.572+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T10:21:47.713124+00:00 [queued]>
[2025-05-15T10:21:49.585+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T10:21:47.713124+00:00 [queued]>
[2025-05-15T10:21:49.585+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 2
[2025-05-15T10:21:49.616+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): fetch_and_store_weather> on 2025-05-15 10:21:47.713124+00:00
[2025-05-15T10:21:49.621+0000] {standard_task_runner.py:60} INFO - Started process 1812 to run task
[2025-05-15T10:21:49.642+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'daily_weather_report', 'fetch_and_store_weather', 'manual__2025-05-15T10:21:47.713124+00:00', '--job-id', '2', '--raw', '--subdir', 'DAGS_FOLDER/daily_weather_dag.py', '--cfg-path', '/tmp/tmp2r_t9h1n']
[2025-05-15T10:21:49.653+0000] {standard_task_runner.py:88} INFO - Job 2: Subtask fetch_and_store_weather
[2025-05-15T10:21:49.757+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.8/site-packages/***/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-05-15T10:21:49.867+0000] {task_command.py:423} INFO - Running <TaskInstance: daily_weather_report.fetch_and_store_weather manual__2025-05-15T10:21:47.713124+00:00 [running]> on host 4a83c4b3f003
[2025-05-15T10:21:50.072+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='daily_weather_report' AIRFLOW_CTX_TASK_ID='fetch_and_store_weather' AIRFLOW_CTX_EXECUTION_DATE='2025-05-15T10:21:47.713124+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-15T10:21:47.713124+00:00'
[2025-05-15T10:21:50.197+0000] {logging_mixin.py:188} INFO - Successfully fetched weather data for Hyderabad
[2025-05-15T10:21:50.291+0000] {logging_mixin.py:188} INFO - Error inserting data: 1049 (42000): Unknown database 'weatherdata'
[2025-05-15T10:21:50.292+0000] {python.py:201} INFO - Done. Returned value was: None
[2025-05-15T10:21:50.301+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=daily_weather_report, task_id=fetch_and_store_weather, execution_date=20250515T102147, start_date=20250515T102149, end_date=20250515T102150
[2025-05-15T10:21:50.369+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2025-05-15T10:21:50.389+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
